import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import TypeIt from "typeit-react";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="-mb-20">
        <nav className="p-8">
          <ul className="flex gap-8">
            <li className="ml-auto">Home</li>
            <li>Portfolio</li>
            <li>About</li>
          </ul>
        </nav>
      </header>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <TypeIt className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Hi! My name is <span className="text-purple-300">Matt Ching</span>,
          <br />
          and I am a software developer. <br />
          Thanks for stopping by.
        </TypeIt>
      </main>

      <section className="container min-h-screen">
        <h1>Portfolio Section</h1>
      </section>
    </>
  );
};

export default Home;
